# Generated by Django 3.0 on 2020-05-03 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('shipped_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(1, 'PROCESSING'), (2, 'SUCESS'), (3, 'FAIL')], default=1)),
            ],
            options={
                'verbose_name': 'shipping',
                'verbose_name_plural': 'shippings',
            },
        ),
    ]
